[package]
name = "graphics-style"
version = "0.1.2"
authors = ["Aster <192607617@qq.com>"]
description = "The styles of all graphics elements"
repository = "https://github.com/oovm/graphics-rs"
documentation = "https://docs.rs/graphics-style"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
palette = "0.6.0"

[dev-dependencies]

[features]
default = []

[package.metadata.wee]
t = "cargo test"
p = "cargo publish --allow-dirty"

