# point, circle, ball, etc. ==========================================================================================
- field: point_size
  typeInner: f32
  default: '1.0'
  docs: Represent the size of a point, default size is 1.0
  details: |-
    The shape of the point is always round.
- field: point_color
  typeInner: RGBA
  docs: Represent the color of a point, default color is black
# point, circle, ball, etc. ==========================================================================================
- field: circle_width
  typeInner: f32
  default: '1.0'
  docs: Represent the width of a circle, default width is 1.0
- field: circle_color
  typeInner: RGBA
  docs: Represent the color of a point, default color is black
# point, circle, ball, etc. ==========================================================================================
- field: triangle_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
- field: triangle_edge_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
- field: triangle_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
# point, circle, ball, etc. ==========================================================================================
- field: disk_fill_color
  typeInner: RGBA
  docs: Represent the color of a disk, default color is black
- field: disk_edge_width
  typeInner: f32
  docs: Represent the edge width of a disk, default width is 1.0
- field: disk_edge_color
  typeInner: RGBA
  docs: Represent the edge color of a disk, default is transparent
# square, rectangle, etc. ==========================================================================================
- field: line_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
- field: line_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
- field: polyline_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
- field: polyline_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
# square, rectangle, etc. ==========================================================================================
- field: square_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0

- field: square_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
- field: square_edge_color
  typeInner: RGBA
  docs: Represent the with of a line, default width is 1.0
- field: square_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
- field: rectangle_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
- field: rectangle_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
- field: rectangle_edge_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
- field: polygon_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
- field: polygon_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
- field: polygon_edge_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
# point, circle, ball, etc. ==========================================================================================
- field: text_size
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
- field: text_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
- field: text_font
  typeInner: f32
  docs: Represent the color of a line, default color is black
# point, circle, ball, etc. ==========================================================================================
- field: background_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
