group:
  # point, circle, ball, etc. ==========================================================================================
  - field: point_style
    derive: Debug, Clone, Copy, PartialEq, Default
    docs: Represent the available style of a point.
    subtype:
      - point_size
      - point_color
  - field: point3d_style
    type: Point3DStyle
    derive: Debug, Clone, Copy, PartialEq, Default
    docs: Represent the available style of a 3d point.
    subtype:
      - point_size
      - point_color
  - field: disk_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a disk.
    subtype:
      - disk_fill_color
      - disk_edge_width
      - disk_edge_color
  - field: ball_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a disk.
    subtype:
      - ball_fill_color
      - ball_edge_width
      - ball_edge_color
  - field: circle_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a circle.
    details: |
      The circle is defined by its center and its radius.
    subtype:
      - circle_size
      - circle_color
  # line, arc, etc. ====================================================================================================
  - field: line_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a line.
    subtype:
      - line_width
      - line_color
  - field: line3d_style
    type: Line3DStyle
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a line.
    subtype:
      - line_width
      - line_color
  - field: polyline_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a line.
    details: |
      The polyline is a collection of points.
    subtype:
      - polyline_width
      - polyline_color
  # polygon ============================================================================================================
  - field: triangle_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a triangle.
    subtype:
      - triangle_fill_color
      - triangle_edge_width
      - triangle_edge_color
  - field: square_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a triangle.
    subtype:
      - square_fill_color
      - square_edge_width
      - square_edge_color
  - field: rectangle_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a rectangle.
    subtype:
      - rectangle_fill_color
      - rectangle_edge_width
      - rectangle_edge_color
  - field: polygon_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a polygon.
    subtype:
      - polygon_fill_color
      - polygon_edge_width
      - polygon_edge_color
  - field: text_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a text.
    subtype:
      - text_color
      - text_size
      - text_font
  - field: background_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a background.
    subtype:
      - background_color
  - field: edge_color
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a style.
    subtype:
      - disk_edge_color
      - triangle_edge_color
      - square_edge_color
      - rectangle_edge_color
      - polygon_edge_color
  - field: edge_width
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a style.
    subtype:
      - disk_edge_width
      - triangle_edge_width
      - square_edge_width
      - rectangle_edge_width
      - polygon_edge_width
  - field: edge_style
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a style.
    subtype:
      - disk_edge_width
      - triangle_edge_color
  - field: fill_color
    derive: Debug, Clone, Copy, PartialEq
    docs: Represent the available style of a style.
    subtype:
      - disk_fill_color
      - triangle_fill_color
      - square_fill_color
      - rectangle_fill_color
      - polygon_fill_color
atom:
  # point, circle, ball, etc. ==========================================================================================
  - field: point_size
    typeInner: f32
    default: '1.0'
    docs: Represent the size of a point, default size is 1.0
    details: |
      The shape of the point is always round.
    derive: Debug, Clone, Copy, PartialEq
  - field: point_color
    typeInner: RGBA
    default:
    docs: Represent the color of a point, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  # point, circle, ball, etc. ==========================================================================================
  - field: circle_width
    typeInner: f32
    default: '1.0'
    docs: Represent the width of a circle, default width is 1.0
    details: ''
    derive: Debug, Clone, Copy, PartialEq
  - field: circle_color
    typeInner: RGBA
    docs: Represent the color of a point, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  # point, circle, ball, etc. ==========================================================================================
  - field: triangle_edge_width
    typeInner: f32
    docs: Represent the with of a line, default width is 1.0
    details: ''
    derive: Debug, Clone, Copy, PartialEq
  - field: triangle_fill_color
    typeInner: RGBA
    docs: Represent the color of a line, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: disk_fill_color
    typeInner: RGBA
    docs: Represent the color of a disk, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: disk_edge_width
    typeInner: f32
    docs: Represent the edge width of a disk, default width is 1.0
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: disk_edge_color
    typeInner: RGBA
    docs: Represent the edge color of a disk, default is transparent
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: line_width
    typeInner: f32
    docs: Represent the with of a line, default width is 1.0
    details: ''
    derive: Debug, Clone, Copy, PartialEq
  - field: line_color
    typeInner: RGBA
    docs: Represent the color of a line, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: square_edge_width
    typeInner: f32
    docs: Represent the with of a line, default width is 1.0
    details: ''
    derive: Debug, Clone, Copy, PartialEq
  - field: square_fill_color
    typeInner: RGBA
    docs: Represent the color of a line, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: square_edge_width
    typeInner: f32
    docs: Represent the with of a line, default width is 1.0
    details: ''
    derive: Debug, Clone, Copy, PartialEq
  - field: square_fill_color
    typeInner: RGBA
    docs: Represent the color of a line, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: rectangle_fill_color
    typeInner: RGBA
    docs: Represent the color of a line, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: rectangle_edge_width
    typeInner: f32
    docs: Represent the with of a line, default width is 1.0
    details: ''
    derive: Debug, Clone, Copy, PartialEq
  - field: rectangle_edge_color
    typeInner: RGBA
    docs: Represent the color of a line, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: polygon_fill_color
    typeInner: RGBA
    docs: Represent the color of a line, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
  - field: polygon_edge_width
    typeInner: f32
    docs: Represent the with of a line, default width is 1.0
    details: ''
    derive: Debug, Clone, Copy, PartialEq
  - field: polygon_edge_color
    typeInner: RGBA
    docs: Represent the color of a line, default color is black
    details: ''
    derive: Debug, Clone, Copy, PartialEq, Default
