# point, circle, ball, etc. ==========================================================================================
- field: point_size
  typeInner: f32
  default: '1.0'
  docs: Represent the size of a point, default size is 1.0
  details: |
    The shape of the point is always round.
  derive: Debug, Clone, Copy, PartialEq
- field: point_color
  typeInner: RGBA
  docs: Represent the color of a point, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
# point, circle, ball, etc. ==========================================================================================
- field: circle_width
  typeInner: f32
  default: '1.0'
  docs: Represent the width of a circle, default width is 1.0
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: circle_color
  typeInner: RGBA
  docs: Represent the color of a point, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
# point, circle, ball, etc. ==========================================================================================
- field: triangle_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: triangle_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: disk_fill_color
  typeInner: RGBA
  docs: Represent the color of a disk, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: disk_edge_width
  typeInner: f32
  docs: Represent the edge width of a disk, default width is 1.0
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: disk_edge_color
  typeInner: RGBA
  docs: Represent the edge color of a disk, default is transparent
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: line_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: line_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: square_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: square_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: square_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: square_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: rectangle_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: rectangle_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: rectangle_edge_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: polygon_fill_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: polygon_edge_width
  typeInner: f32
  docs: Represent the with of a line, default width is 1.0
  details: ''
  derive: Debug, Clone, Copy, PartialEq
- field: polygon_edge_color
  typeInner: RGBA
  docs: Represent the color of a line, default color is black
  details: ''
  derive: Debug, Clone, Copy, PartialEq
